### ISSUE TITLE
Special characters in store name break (at least) sofort. payment method

### ISSUE THREAD

**Issue by darinda** [wirecard/magento-ee#31]
The descriptor for payment transactions is composed of [store name](https://github.com/wirecard/magento-ee/blob/d8744ed4b154276a82c46426b60520c98e5f13e3/lib/WirecardEE/PaymentGateway/Service/PaymentHandler.php#L160) and [order id](https://github.com/wirecard/magento-ee/blob/d8744ed4b154276a82c46426b60520c98e5f13e3/lib/WirecardEE/PaymentGateway/Service/PaymentHandler.php#L161).

Many shops use some kind of special chars in their store name, from tildes, underscores, single quotes to even emojis. Since the descriptor is never sanitized before transmitting to Wirecard this makes (at least!) payment method sofort. unusable in such shops.

this is due to the limitation of Sofort's API (https://www.sofort.com/integrationCenter-ger-DE/content/view/full/3047/#h6-1) where the descriptor only allows certain characters to be used in the descriptor.

Therefore, currently, sofort. payment will be non-functional in a very high amount of magento shops (namely every shop that uses any character other than the ones allowed by sofort in their store name).

 The descriptor string will need to be sanitized in the payment handler to fix this problem.

**Comment by tomazpu** [comment]
Hello @darinda, 

thank you for you contribution. Sorry for the late reply. We are aware of the issue with special chars, a fix to this issue is already released in the [paymentSDK](https://github.com/wirecard/paymentSDK-php). We will try to provide a new release as soon as possible.

Kid regards,
Wirecard Shop Systems Team

**Comment by darinda** [comment]
Dear @tomazpu ,

thanks for providing the updated version. Unfortunately, even in release 1.2.2 the issue is still present. I updated the module and re-tried, the error arises:

Error-code: 400.1150
Description: Unsupported characters found in the request. Please check your input.

If needed i willl be happy to provide more info via non-public channels.

best regards

**Comment by tomazpu** [comment]
Hello @darinda, 

thank you for reporting the issue. Sorry for the late reply. You right, the provided fix is not working as expected. We don't want you to wait for another release so i will provide you the fix here, and later we will make a release which will fix the issue.

Go to the class SofortTransaction.php and in the line 46 paste the following code in as the regex "/[^a-zA-Z0-9\s\+\,\-\.\Ä\Ö\Ü\ä\ö\ü]/u". This will do the trick. We made one more improvement in the Risk.php method sanitizeDescriptor() see the code below and if you want you can also replace it.
`
    private function sanitizeDescriptor($descriptor, $length, $regex)
    {
        $sanitizedDescriptor =  preg_replace($regex, '', $descriptor);

        //Remove double spaces and cut to width
        return mb_strimwidth(preg_replace('/\s+/', ' ', $sanitizedDescriptor), 0, $length);
    }
`
The improvement is that double spaces get removed. Once again, thank you.
Sorry for the long response time.
Best regards Tomaz

**Comment by darinda** [comment]
@tomazpu The `SofortTransaction.php` is part of [the payment sdk](https://github.com/wirecard/paymentSDK-php). The updated regex does not seem to have been [implemented there](https://github.com/wirecard/paymentSDK-php/blob/master/src/Transaction/SofortTransaction.php#L24) yet.

Therefore, even the latest release [v 1.2.3](https://github.com/wirecard/magento-ee/releases/tag/1.2.3) does not yet include it. 

I'm a little confused on how to proceed here. Of course i'm trying to avoid having to manually apply the patch you're suggesting in your latest comment, since it will be overridden by every update.

Will that fix be included in the payment sdk anytime soon (and will there be a new release of the magneto module, then) or is it non required anymore?

**Comment by tomazpu** [comment]
@darinda 

Hello, thank you for your input. We just released the paymentSDK version 3.7.3. There the fix for the descriptor is included. In the next day its are goal to also release the magento plugin with the new paymentSDK.

Best regards Tomaz

**Comment by pretzelhands** [comment]
Hi @darinda,

this issue is resolved with release 1.2.4! Please update your module and its dependencies or use the package provided on the [release page](https://github.com/wirecard/magento-ee/releases/tag/1.2.4) as it includes the latest version of paymentSDK.

Best regards,
Richard
