### ISSUE TITLE
Install via modman and allow symlinks?

### ISSUE THREAD

**Issue by roman204** [wirecard/magento-ee#35]
I am bit confused about this extension and the suggested installation. 
Let me explain my thoughts:
The [installation](https://github.com/wirecard/magento-ee/wiki/Installation#installing-the-extension) document describes that symlinks have to be enabled? 
Enable symlinks is not suggested and marked as a critical security risk. See here: https://magento.com/security/patches/supee-9767 and https://magento.stackexchange.com/questions/176952/supee-9767-modman-and-symlinks

Also the installation process is strange for me, against all other extensions you decide to let the developer install some dependencies via composer directly and than install it via modman?! Why did you choose that way? Is it because of modman which do symlink extensions normally? Composer is a dependency manager why do you not let handle him the dependencies?

If you have dependencies in your module the recommended way is to define those dependencies in composer.json and let composer install them including the module. In your case installation via modman is not an option.

**Comment by roman204** [comment]
If you really suggest installation via modman, recommend the modman copy strategy and not "enable symlinks" in magento.

**Comment by jakubpolomsky** [comment]
Hello Roman,

we will adapt the documentation to state also the `--copy` option. What we can't change is the dependency management. It will still be necessary to install the libraries via composer as the clone command of modman doesn't clone the dependencies. We will close this issue after the documentation is updated.

Thank you for your contribution!

Team Wirecard

**Comment by roman204** [comment]
Hi Wirecard Team,

i made a version which can be installed via composer, you can take a look at my fork.

**Comment by roman204** [comment]
Hi again,

the way you want developers to install your extension is not useful... only one keyword GIT! 
I managed to install it but not the way your installdocs recommend.
