### ISSUE TITLE
test credentials not work 

### ISSUE THREAD

**Issue by roman204** [wirecard/magento-ee#40]
cause of hard coded url in check_credentials.js line: 20

![image](https://user-images.githubusercontent.com/584168/59920842-21ea8400-942c-11e9-916f-d5f93304da9d.png)

![image](https://user-images.githubusercontent.com/584168/59920778-e8197d80-942b-11e9-8abf-4c6cf87dc29f.png)

**Comment by tomazpu** [comment]
Hello @roman204, 

thank you for reporting the issue. We will look into it and provide a fix. Sorry for the late reply. If you need the fix quick please write me here and we will provide you with a code snippet.

Thank you again.
Best regards, 
Tomaz

**Comment by rinnhofer** [comment]
Hello @roman204 ,

today we released a new version of our magento-ee extension, which should resolve this issue.
https://github.com/wirecard/magento-ee/releases/tag/1.2.3

Best regards,
Wirecard Shop Systems Team
