### ISSUE TITLE
missing jQuery

### ISSUE THREAD

**Issue by riconeitzel** [wirecard/magento-ee#42]
running on Magento 1.9.0.1

this segment

https://github.com/wirecard/magento-ee/blob/ce2c8ec8a2df6e9bfa535dc4691fe1e329061060/app/design/adminhtml/default/default/layout/WirecardEE/payment_gateway.xml#L13

triggers a 404 … the file isn't there and it's not part of the extension as well.

**Comment by vitali-graz** [comment]
Hi @riconeitzel 
thank you for bringing up this issue. We are currently evaluating and prioritizing this appropriately.
Best regards,
Wirecard Shop Systems Team

**Comment by riconeitzel** [comment]
Hi @vitali-graz,

are there any updates/progress yet? 

Rico

**Comment by serucee** [comment]
Hi @riconeitzel ,

we are currently testing a fix for the described issue and will inform you once it is released. But be aware that magento 1.9.01 is not officially supported by our extension.

Best regards,
Wirecard Shop Systems Team

**Comment by riconeitzel** [comment]
Thanks for the heads up … thought you're supporting 1.9.x 

my mistake! I'll propose an upgrade to the merchant.

**Comment by serucee** [comment]
Hi, 

you can find the tested versions and compatibility under the releases. We might add this to the readme badges as well.
Thank you for your feedback!

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi,

the issue was resolved in the latest released version 1.3.0.
Regarding the compatible versions - those will be added to the readme.
If you have any further questions feel free to reopen this issue or open a new one.

Best regards,
Wirecard Shop Systems Team
