### ISSUE TITLE
< php71 incompatibility

### ISSUE THREAD

**Issue by riconeitzel** [wirecard/magento-ee#43]
PHP 7.1 is required for this extension due to this line:

https://github.com/wirecard/magento-ee/blob/ce2c8ec8a2df6e9bfa535dc4691fe1e329061060/composer.json#L9

Magento doesn't support 7.1, only 7.2 and also only the most recent version. 

The requirements in the wirecard documentation talk about php5.6+

**Comment by serucee** [comment]
Hi,

when trying to install the plugin via composer i am able to install it with php 7.2 and 7.3.
The payment-sdk-php 3.6.6 has the php requirement set to 5.6+
Could you provide me with the error message displayed?

Best regards,
Wirecard Shop Systems Team

**Comment by riconeitzel** [comment]
Hi!

Please try to run composer install with php7.0 or php5.6

As I said the issue occurs if it’s < (less than) 7.1

Thanks,
Rico

**Comment by riconeitzel** [comment]
here's composer's response

```bash  
$:/ composer70 install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - myclabs/php-enum 1.7.1 requires php >=7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
    - myclabs/php-enum 1.7.1 requires php >=7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
    - Installation request for myclabs/php-enum 1.7.1 -> satisfiable by myclabs/php-enum[1.7.1].

$:/ composer70 why myclabs/php-enum
wirecard/payment-sdk-php  3.6.6  requires  myclabs/php-enum (^1.5.0)  
```

**Comment by serucee** [comment]
Hi,

thanks for providing additional information. We are going to release a SDK version (3.7.2) and an update for the magento-ee extension soon which solves this issue and inform you once done.

Best regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @riconeitzel ,

today we released a new version of our magento-ee extension, which should resolve this issue.
https://github.com/wirecard/magento-ee/releases/tag/1.2.3

Best regards,
Wirecard Shop Systems Team
