### ISSUE TITLE
Unable to include the Composer autoloader

### ISSUE THREAD

**Issue by mybinaryromance** [wirecard/magento-ee#48]
On manual install the process dies with "Unable to include the Composer autoloader". A magento 1 CE extension should not require composer at all, it is not a system requirement...

Stack trace:
a:5:{i:0;s:42:"Unable to include the Composer autoloader.";i:1;s:1294:"#0 /..../app/code/community/WirecardEE/PaymentGateway/Model/Observer.php(22): WirecardEE_PaymentGateway_Model_Observer->registerComposerAutoloader()
#1 /..../app/code/core/Mage/Core/Model/App.php(1358): WirecardEE_PaymentGateway_Model_Observer->controllerFrontInitBefore(Object(Varien_Event_Observer))
#2 /..../app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(WirecardEE_PaymentGateway_Model_Observer), 'controllerFront...', Object(Varien_Event_Observer))
#3 /..../app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('controller_fron...', Array)
#4 /..../app/code/core/Mage/Core/Controller/Varien/Front.php(128): Mage::dispatchEvent('controller_fron...', Array)
#5 /..../app/code/core/Mage/Core/Model/App.php(764): Mage_Core_Controller_Varien_Front->init()
#6 /..../app/code/core/Mage/Core/Model/App.php(1113): Mage_Core_Model_App->_initFrontController()
#7 /..../app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Model_App->getFrontController()
#8 /..../app/Mage.php(686): Mage_Core_Model_App->run(Array)
#9 /..../index.php(129): Mage::run('eu_default', 'store')
#10 {main}";s:3:"url";s:6:"/admin";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:10:"eu_default";}

**Comment by mybinaryromance** [comment]
Apparently this happens because /lib/WirecardEE/vendor/autoload,php is not found. /lib/WirecardEE/vendor is completely missing from the repositiory... What am I missing?

**Comment by mybinaryromance** [comment]
Looks like https://github.com/wirecard/paymentSDK-php needs to be installed, plus guzzle http stuff etc. Would be nice to have a hint on that in the manual installation instructions, guys...

**Comment by jakubpolomsky** [comment]
Hello and thank you for your report.

The [installation guide](https://github.com/wirecard/magento-ee/wiki/Installation) describes this in the point 3. of the recommended procedure. If you used the copy method, the vendor directory is already included in the package. Could you find the information in the guides?

Kind regards,
Wirecard Shop-systems Team

**Comment by mybinaryromance** [comment]
I tried both the recommended procedure (it dies with a 'no pull request permission on github' error) and then turned to the manual installation method as described in the installation guide.

The Download magento-wirecard-ee.zip does not include vendor directory. The manual installation method description does not mention the dependencies.
Please update the installation guide with links to the reqired packages plus a dummy autoload.php file so one has a chance to see through this stuff ;)

**Comment by jakubpolomsky** [comment]
The pull request permission error means, that there was some error while executing the commands. As during the steps described in the guide are no pull requests created and as the repositories are public thus cloning the repos should be possible from every server with internet access.

Regarding the vendor directory the files of autoloaded packages reside in `lib/WirecardEE/vendor` and the autoload.php is also located in that directory. The vendor files are used by the observer `app/code/community/WirecardEE/PaymentGateway/Model/Observer.php` and in the line 32 is also stated, that the location is correct. Maybe was there an error copying or extracting the files?

The plugins are tested every night and the described installation procedures are being used during the automated tests. Can you please confirm that the plugin works properly now?

**Comment by mybinaryromance** [comment]
No, the plugin is not working yet. Please update the description for the manual (no composer) installation process so that it is possible to install the plugin following the instructions. OR provide a complete installation archive, including vendor directory, other possible dependencies and autoload.php (which is reqired by the module).

**Comment by jakubpolomsky** [comment]
After starting a fresh shop, copying the files of the latest release and extracting them I couldn't reproduce any errors. If your problems still persist, please provide the shop version, plug-in version and steps to reproduce the issue. So far I did not find anything missing either in the documentation or in the package.

Kind regards

**Comment by mybinaryromance** [comment]
okay, thanks!
