### ISSUE TITLE
Install via modman throws error

### ISSUE THREAD

**Issue by Sharkozp** [wirecard/magento-ee#51]
I trying to install this module via modman and in in config it presents:
`skin/adminhtml/default/default/images/WirecardEE                            skin/adminhtml/default/default/images/WirecardEE`
 https://github.com/wirecard/magento-ee/blob/e90aa0427793dc34cd1bae2a4c9b2050ab0a5de5/modman#L17

but this directory don't exist in this project

**Comment by mmodler** [comment]
+1

**Comment by serucee** [comment]
Hi,

thank you for your input. We will look into the described issue and keep you updated.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi,

the issue was resolved in the latest released version 1.3.0.
If you have any further questions feel free to reopen this issue or open a new one.

Best regards,
Wirecard Shop Systems Team
