### ISSUE TITLE
jQuery error in admin section

### ISSUE THREAD

**Issue by Sharkozp** [wirecard/magento-ee#52]
If Magento patched with SUPPE-10975 (Magento 1.9.4.0), you will get error on payments method in Admin section.
With this patch/version jQuery library was renamed into jquery-1.12.1, but in layout update is using jquery-1.12.0:
https://github.com/wirecard/magento-ee/blob/e90aa0427793dc34cd1bae2a4c9b2050ab0a5de5/app/design/adminhtml/default/default/layout/WirecardEE/payment_gateway.xml#L12

**Comment by serucee** [comment]
Hi,

thank you for your input. We will look into the described issue and keep you updated.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi,

the issue was resolved in the latest released version 1.3.0.
If you have any further questions feel free to reopen this issue or open a new one.

Best regards,
Wirecard Shop Systems Team
