### ISSUE TITLE
What about Przelewy24?

### ISSUE THREAD

**Issue by kowalschik** [wirecard/magento-ee#54]
Hello,

we're forced to change the module to ee .. but what about przelewy24? When is it implemented or is the plan to use the old module for p24?

**Comment by vitali-graz** [comment]
Hello @kowalschik ,

Thank you for your your inquiry. The issue of P24 is known and is currently being discussed internally.
As soon as I have news I will update this ticket.

Best regards,
Wirecard Shop Systems Team

**Comment by mvenghaus** [comment]
same here

**Comment by vitali-graz** [comment]
Hello @kowalschik and @mvenghaus ,

Thank you for your interest in P24. We are currently focusing on PSD2-related topics. Thus, P24 is on hold.
I will update this ticket once the task has been prioritized in.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @kowalschik  and @mvenghaus ,

sorry for the delay. P24 got added in the latest release https://github.com/wirecard/magento-ee/releases/tag/v2.0.0.

BR
