### ISSUE TITLE
Version Number in config doesn't match git Tag

### ISSUE THREAD

**Issue by riconeitzel** [wirecard/magento-ee#59]
https://github.com/wirecard/magento-ee/blob/cd8dc1a5589c61207ce7d4a7eb094f321bd56911/app/code/community/WirecardEE/PaymentGateway/etc/config.xml#L12

Git Tag 1.2.4 … config.xml 1.2.3

**Comment by serucee** [comment]
Hi,

this is a known issue and will be fixed with the next release. Thank you for your feedback.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi,

the issue was resolved in the latest released version 1.3.0.
If you have any further questions feel free to reopen this issue or open a new one.

Best regards,
Wirecard Shop Systems Team
