### ISSUE TITLE
Crash when placing order without shipping address

### ISSUE THREAD

**Issue by rolandjaeger** [wirecard/magento-ee#62]
Hi,

when placing an order without a shipping address (we sell virtual products in our shop and do not require our customers to enter a shipping address), the module will crash in GatewayController.php on line 222:                 `$threedsHelper->getAddressFirstUsed($order->getShippingAddress()->getCustomerAddressId()),`

Prepopulating a variable with something like this should fix the crash at this point:
```
if (!$order->getIsVirtual() && $order->getShippingAddress()) {
            $addressFirstUsed = $threedsHelper->getAddressFirstUsed($order->getShippingAddress()->getCustomerAddressId());
} else {
            $addressFirstUsed = false;
}
```
This is how other payment modules (e.g. PayPal) handle this situation but I am not sure if there may be more problems waiting further downstream. So far, this fix seems to work but it has not been fully tested.

Any suggestions?

Thank you,
Roland

**Comment by serucee** [comment]
Hi,

thank you for your feedback. We will look into the described issue, test the suggested solution and keep you updated.

Best regards,
Wirecard Shop Systems Team

**Comment by Sharkozp** [comment]
It is also crashed when customer registered and don't have address. And he adds new address via checkout process.

After placing order I got issue on this URL:

URL:
{{magento}}/paymentgateway/gateway/index/method/creditcard/

`Fatal error: Uncaught TypeError: Argument 1 passed to Wirecard\PaymentSdk\Entity\AccountInfo::setShippingAddressFirstUse() must be an instance of DateTime, null given, called in /var/www/shop/lib/WirecardEE/PaymentGateway/Mapper/AccountInfoMapper.php on line 180 and defined in /var/www/shop/lib/WirecardEE/vendor/wirecard/payment-sdk-php/src/Entity/AccountInfo.php:209 
Stack trace: 
#0 /var/www/shop/lib/WirecardEE/PaymentGateway/Mapper/AccountInfoMapper.php(180): Wirecard\PaymentSdk\Entity\AccountInfo->setShippingAddressFirstUse(NULL) 
#1 /var/www/shop/lib/WirecardEE/PaymentGateway/Mapper/AccountInfoMapper.php(123): WirecardEE\PaymentGateway\Mapper\AccountInfoMapper->addAuthenticatedUserD in /var/www/shop/lib/WirecardEE/vendor/wirecard/payment-sdk-php/src/Entity/AccountInfo.php on line 209`

**Comment by Sharkozp** [comment]
Also if I go in Incognito mode to this URL:

I got crash:
`Fatal error: Uncaught Error: Call to a member function getCustomerAddressId() on boolean in /var/www/shop/app/code/community/WirecardEE/PaymentGateway/controllers/GatewayController.php:222 
Stack trace: 
#0 /var/www/shop/app/code/community/WirecardEE/PaymentGateway/controllers/GatewayController.php(64): WirecardEE_PaymentGateway_GatewayController->buildOrderSummary(Object(Mage_Sales_Model_Order), Object(WirecardEE\PaymentGateway\Payments\CreditCardPayment)) 
#1 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Action.php(418): WirecardEE_PaymentGateway_GatewayController->indexAction() 
#2 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index') 
#3 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Front.p in /var/www/shop/app/code/community/WirecardEE/PaymentGateway/controllers/GatewayController.php on line 222`

**Expected result:**
It must redirect for ex. to home page without crash

**Comment by serucee** [comment]
Hi @rolandjaeger  ,
@Sharkozp 

we are going to release version 1.3.1 in the course of the next week which will resolve this issue. I am sorry for the delay.

Best regards,
Wirecard Shop Systems Team

**Comment by pxfm** [comment]
Hi @serucee !

Is there any news about version 1.3.1 and this fix?

Thanks in advance,
Fernando

**Comment by serucee** [comment]
Hi @rolandjaeger ,
@Sharkozp ,
@pxfm ,

We are sorry for the delay. The latest release (1.3.1) resolves this issue. If you have further questions or issues after updating, feel free to reopen the issue or create a new one.

Best regards,
Wirecard Shop Systems Team
