### ISSUE TITLE
there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT

### ISSUE THREAD

**Issue by mvenghaus** [wirecard/magento-ee#64]
getting this error

Error in file: "/var/www/html/app/code/community/WirecardEE/PaymentGateway/sql/wirecardee_paymentgateway_setup/upgrade-1.2.0-1.3.0.php" - SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

#0 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(437): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '1.2.0', '1.3.0')
#2 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(320): Mage_Core_Model_Resource_Setup->_upgradeResourceDb('1.2.0', '1.3.0')
#3 /var/www/html/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/html/app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 /var/www/html/app/Mage.php(694): Mage_Core_Model_App->run(Array)
#7 /var/www/html/index.php(90): Mage::run('xxx', 'website')
#8 {main}

**Comment by serucee** [comment]
Hi @mvenghaus ,

thank you for your feedback. Could you provide us with the MySQL version you currently use?

Best regards,
Wirecard Shop Systems Team

**Comment by mvenghaus** [comment]
mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by serucee** [comment]
Hi,

thank you for your quick response. This seems to be caused by legacy restrictions that were removed in MySQL 5.6.5 (2012-04-10, Milestone 8). If possible, please update your database and check if the issue persists. Meanwhile we will work on a solution - but be aware that MariaDB is not officially supported by either Magento 1.X or our extension.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi,

since there was no further response this issue is closed. If you have any further questions or issues, feel free to reopen it or create a new issue.

Best regards,
Wirecard Shop Systems Team
