### ISSUE TITLE
Google Pay / Apple Pay

### ISSUE THREAD

**Issue by mmodler** [wirecard/magento-ee#66]
Hi,

one of our customers asked wirecard for Google Pay / Apple Pay, which is supported.

But when will Google Pay / Apple Pay be implemented into the magento-ee extension?

Thanks!

**Comment by vitali-graz** [comment]
Hi @mmodler ,
Thank you for your interest in Apple Pay and Google Pay.
Both topics are being actively evaluated but as of now no concrete dates can be named for implementation in our extensions.
If you are interested in implementing the payment methods into the SDK and the extension yourself, we would of course appreciate the pull request as it would lead to earlier release.
Best regards,
Wirecard Shop Systems Team
