### ISSUE TITLE
Impossible if condition in success.phtml

### ISSUE THREAD

**Issue by rolandjaeger** [wirecard/magento-ee#68]
Hi,

apart from being very annoying to show the Wirecard specific order result on top of the success page, there is a small bug in it that prevents the additional message from being shown.

In /app/design/frontend/base/default/template/WirecardEE/checkout/success.phtml in line 27 the following if condition
`if ($this->getOrderStatusLabel() === Mage_Sales_Model_Order::STATE_PENDING_PAYMENT) {`
should be changed to
`if ($this->getOrderState() === Mage_Sales_Model_Order::STATE_PENDING_PAYMENT) {`

Best,
Roland

**Comment by rinnhofer** [comment]
Hello @rolandjaeger ,

thank you for your input. We will look into this issue as soon as possible.

Kind regards,
Wirecard Shop Systems

**Comment by serucee** [comment]
Hi @rolandjaeger ,

the issue got fixed in the latest release https://github.com/wirecard/magento-ee/releases/tag/v2.0.0

BR
