### ISSUE TITLE
Refund not possible

### ISSUE THREAD

**Issue by pointia** [wirecard/magento-ee#71]
Hi,

if this module is installed it is not possible to create a refund (creditmemo) by code. It only works in adminhtml.

Reason for that is the following observer
```
            <sales_order_payment_refund>
                <observers>
                    <wirecard_ee_refund>
                        <type>singleton</type>
                        <class>paymentgateway/backendOperation</class>
                        <method>refund</method>
                    </wirecard_ee_refund>
                </observers>
            </sales_order_payment_refund>
```
The backendOperation class then has following refund method

```
 /**
     * Refunds are processed by finding proper transactions and apply the operation on each of them.
     *
     * @param Varien_Event_Observer $observer
     *
     * @return Action[]
     * @throws Mage_Core_Exception
     * @throws \WirecardEE\PaymentGateway\Exception\UnknownPaymentException
     *
     * @since 1.0.0
     */
    public function refund(Varien_Event_Observer $observer)
    {
        $creditMemo     = $observer->getData('creditmemo');
        $creditMemoPost = Mage::app()->getRequest()->getPost('creditmemo', []);
        if (! ($creditMemo instanceof Mage_Sales_Model_Order_Creditmemo) || empty($creditMemoPost['items'])) {
            $this->throwError("Unable to process backend operation (refund)");
        }
...
```

In this context it makes no sense to get the POST variables from the request. It does not matter if we would like to refund a wirecard payment method or any other method (e.g. checkmo). This observer always throws "Unable to process backend operation (refund)".

So in general this behavior should be the same for any integration (e.g. API, ERP, ...)

I would highly appreciate if you could fix that issue with high priority because we can't do any refund right now.

**Comment by serucee** [comment]
Hi,

thank you for your feedback and the detailed explanation! We will look into this issue as soon as possible and keep you updated.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @pointia ,

we are going to release version 1.3.1 in the course of the next week which will resolve this issue. I am sorry for the delay.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @pointia ,

the latest release (1.3.1) includes the fix for this issue.

Best regards,
Wirecard Shop Systems Team
