### ISSUE TITLE
Creditcard Seamless Form button not working (magento theme related issue)

### ISSUE THREAD

**Issue by stephansteiner** [wirecard/magento-ee#72]
On some themes, the css styles of submit button in the wirecard seamless form where you enter credit card data may cause issues with third party AjaxCart plugins.

This piece of code is not working in some themes:
```
<button id="wirecardee-credit-card--form-submit" class="button btn-cart" type="submit">
Submit
</button>
```

This piece of code fixes the problem (changed the cass class of the button):
```
<button id="wirecardee-credit-card--form-submit" class="button" type="submit">
Submit
</button>
```

**Comment by serucee** [comment]
Hi @stephansteiner 

sorry for the delay. The issue got fixed in the latest release https://github.com/wirecard/magento-ee/releases/tag/v2.0.0

BR
